### ISSUE TITLE
325 dev issue

### ISSUE THREAD

**Issue by sqweelygig** [sqweelygig/syncbot-sandbox#8]
Another issue

**Comment by sqweelygig** [comment]
comment on GH

**Comment by sqweelygig** [comment]
comment

**Comment by lurch** [comment]
Wooh, funky! :grinning: 

**bold** _italic_ ;-)

**Comment by sqweelygig** [comment]
Wooh, funky! 🙂 

**bold** *italic*

With the process running!

**Comment by sqweelygig** [comment]
emoji 👍

**Comment by sqweelygig** [comment]
**formatting**

**Comment by sqweelygig** [comment]
blank

lines

**Comment by sqweelygig** [comment]
blank

lines

**Comment by sqweelygig** [comment]
new
line

**Comment by sqweelygig** [comment]
new
line

**Comment by sqweelygig** [comment]
new
line

**Comment by sqweelygig** [comment]
new
line

**Comment by sqweelygig** [comment]
new
line

**Comment by sqweelygig** [comment]
new
line 1351

**Comment by sqweelygig** [comment]
new
line 1733

**Comment by lurch** [comment]
ping
> ping

**Comment by sqweelygig** [comment]
Wow, handled that surprisingly well

**Comment by sqweelygig** [comment]
It would seem you're not allowed to whisper on my Front instance, which is unsurprising since you don't have an account!

**Comment by lurch** [comment]
Is it possible to change the avatar that syncbot uses, so it's easier to differentiate comments from @sqweelygig and comments from @syncbot ?
(@jviotti also had a similar issue recently where his avatar was being used for the resin-concourse status notifications - which he's now managed to fix)

**Comment by sqweelygig** [comment]
Are you asking about differentiating between syncbot-as-syncbot vs syncbot-as-sqweelygig

**Comment by lurch** [comment]
To clarify, I specifically mean on GH...
![image](https://user-images.githubusercontent.com/476186/35874712-2c5937c0-0b65-11e8-950f-ff629a81900e.png)

**Comment by sqweelygig** [comment]
Gotcha!
